openapi: 3.0.0
info:
  title: API Users
  version: "1.0"
  description: Endpoints para gestionar usuarios, obtener información por ID o el usuario actual autenticado.
servers:
  - url: http://nexusroot.bucaramanga.upb.edu.co/
    description: Servidor de producción

paths:
  /users/{id}:
    get:
      summary: Obtener usuario por ID
      description: Retorna la información de un usuario específico por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario a consultar
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              example:
                id: "5"
                username: "Juan"
                email: "juan@email.com"
        '400':
          description: ID inválido
          content:
            application/json:
              example:
                error: "User ID must be a number"
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              example:
                error: "User not found"
        '500':
          description: Error interno
          content:
            application/json:
              example:
                error: "Error inesperado"

  /users/me:
    get:
      summary: Obtener usuario actual
      description: Retorna la información del usuario autenticado mediante token.
      responses:
        '200':
          description: Datos del usuario actual
          content:
            application/json:
              example:
                id: "5"
                username: "Juan"
                email: "juan@email.com"
        '401':
          description: Usuario no autenticado
          content:
            application/json:
              example:
                error: "No token provided"
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              example:
                error: "User not found"
        '500':
          description: Error interno
          content:
            application/json:
              example:
                error: "Error inesperado"

components:
  schemas:
    User:
      type: object
      description: Representa un usuario del sistema
      properties:
        id:
          type: string
          description: Identificador único del usuario
        username:
          type: string
          description: Nombre de usuario
        email:
          type: string
          description: Correo electrónico del usuario
      required:
        - id
        - username
        - email
